### ISSUE TITLE
Cannot type the '@' symbol using a Canadian French keyboard layout

### ISSUE THREAD

**Issue by jofrank87** [chabou/hyper-pane#31] opened 2018-07-16 13:57 UTC
When I'm using the Canadian French keyboard layout, on Windows 10, I cannot type the '@' symbol, while using this plugin.

I did some light digging through the code and notice that it seems to be related to the **onMoveToPane** function. For now, I'm disabling the onMoveToPane function, by commenting the **map.onMoveToPane** line, in the plugin **index.js** file, and it fixes the issue, but I'm pretty sure this isn't the right way to solve the problem.

```
exports.mapTermsDispatch = (dispatch, map) => {
  //map.onMoveToPane = onMoveToPane(dispatch);
  //map.onSwitchWithActiveSession = onSwitchWithActiveSession(dispatch);
  map.onMoveToDirectionPane = onMoveToDirectionPane(dispatch);
  map.onMaximizePane = onMaximizePane(dispatch);
  return map;
};
```

**Comment by chabou** [comment] 2018-12-11 16:05
I think that I understood your issue.

To enter `@` you are using `AltGr+2` or something like this.
By default, `hyper-pane` is configured with `ctrl+alt` prefix to jump to a given term. `ctrl+alt+3` for the term number 3 for example.

But on Windows `AltGR` === `ctrl+alt`

You have to change `jump_prefix` in plugin configuration part of you `.hyper.js`

We have to put better default shortkeys for Windows.

**Comment by chabou** [comment] 2018-12-11 16:06
In fact, this is a duplicate of #29

**Closed by chabou** 2018-12-11 16:06 UTC
Labels: bug
